apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-agent
  namespace: discovery-agent
  labels:
    app: discovery-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discovery-agent
  namespace: discovery-agent
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discovery-agent
  namespace: discovery-agent
subjects:
  - kind: ServiceAccount
    name: discovery-agent
    namespace: discovery-agent
roleRef:
  kind: Role
  name: discovery-agent
  apiGroup: rbac.authorization.k8s.io
